# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: @/plugins/teb/simplecounsel/models/post/columns.yaml

# Model Class name
modelClass: Teb\SimpleCounsel\Models\Post

# List Title
title: teb.simplecounsel::lang.form.posts

# Link URL for each record
recordUrl: teb/simplecounsel/posts/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 10

# Displays the list column set up button
showSetup: true

# Filter widget configuration
filter: config_filter.yaml

showTree: false

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt
